### ISSUE TITLE
Error during gospider execution

### ISSUE THREAD

**Issue by gitevildelta** [jaeles-project/gospider#68]
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 6 [running]:
sync.(*WaitGroup).Wait(0xc00003d690?)
	/usr/lib/go/src/sync/waitgroup.go:118 +0x7f
 github.com/gocolly/colly/v2.(*Collector).Wait(0xc0002f0120?)
 	/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:812 +0x25
 main.run.func1()
 	/go/pkg/mod/github.com/jaeles-project/gospider@v1.1.6/main.go:223 +0x515
 created by main.run
 	/go/pkg/mod/github.com/jaeles-project/gospider@v1.1.6/main.go:155 +0x687

**Comment by Autumn-27** [comment]
have you solved it
